apiVersion: v1
kind: Service
metadata:
  name: inventario-pt-service
spec:
  type: LoadBalancer
  selector:
    app: inventario-pt-app
    pod: inventario-pt-pod
  ports:
    - name: container-port
      targetPort: 80
      port: 80